name: pomodoro_app
description: "A simple 25+5 & 50+10 Pomodoro Timer App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/icon.png"
  adaptive_icon_background: "#121212"
  adaptive_icon_foreground: "lib/icon.png"

flutter:
  uses-material-design: true
  
